### 기본 설정

In [21]:
import numpy as np
import pandas as pd

In [22]:
train = pd.read_csv('../dataset/house_prices/train.csv')
test = pd.read_csv('../dataset/house_prices/test.csv')

### Data 살펴보기

In [23]:
train.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1460.000000,1460.000000,1201.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1452.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,730.500000,56.897260,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.685262,443.639726,...,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,421.610009,42.300571,24.284752,9981.264932,1.382997,1.112799,30.202904,20.645407,181.066207,456.098091,...,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,365.750000,20.000000,59.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,730.500000,50.000000,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,...,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,1095.250000,70.000000,80.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,166.000000,712.250000,...,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

In [24]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     1452 non-null   object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [25]:
train.isnull().sum()

Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
                ...
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 81, dtype: int64

### Imputation (`most_frequent`)

In [26]:
from sklearn.impute import SimpleImputer

columnList = train.columns
imputer = SimpleImputer(strategy="most_frequent")
train = pd.DataFrame(imputer.fit_transform(train))
train.columns = columnList

In [27]:
train.describe()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
count,1460,1460,1460,1460.0,1460,1460,1460,1460,1460,1460,...,1460,1460,1460,1460,1460,1460,1460,1460,1460,1460
unique,1460,15,5,110.0,1073,2,2,4,4,2,...,8,3,4,4,21,12,5,9,6,663
top,1,20,RL,60.0,7200,Pave,Grvl,Reg,Lvl,AllPub,...,0,Gd,MnPrv,Shed,0,6,2009,WD,Normal,140000
freq,1,536,1151,402.0,25,1454,1419,925,1311,1459,...,1453,1456,1336,1455,1408,253,338,1267,1198,20

### Encoding

In [31]:
# object형을 다 categorical data로 바꿔주기

for col in train.columns:
    if(train[col].dtype == 'O'):
        train[col] = train[col].astype('category').cat.codes
        
train.describe()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
count,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,729.500000,4.166438,3.028767,38.936986,492.102740,0.995890,0.028082,1.942466,2.777397,0.000685,...,0.019178,1.995890,1.889726,1.996575,0.290411,5.321918,1.815753,7.513014,3.770548,292.828767
std,421.610009,4.161951,0.632017,19.057976,300.719399,0.063996,0.165264,1.409156,0.707666,0.026171,...,0.309173,0.082687,0.440610,0.086762,1.793077,2.703626,1.328095,1.552100,1.100854,169.719317
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,364.750000,0.000000,3.000000,31.000000,229.750000,1.000000,0.000000,0.000000,3.000000,0.000000,...,0.000000,2.000000,2.000000,2.000000,0.000000,4.000000,1.000000,8.000000,4.000000,151.750000
50%,729.500000,4.000000,3.000000,34.000000,476.500000,1.000000,0.000000,3.000000,3.000000,0.000000,...,0.000000,2.000000,2.000000,2.000000,0.000000,5.000000,2.000000,8.000000,4.000000,273.000000
75%,1094.250000,6.000000,3.000000,50.000000,737.250000,1.000000,0.000000,3.000000,3.000000,0.000000,...,0.000000,2.000000,2.000000,2.000000,0.000000,7.000000,3.000000,8.000000,4.000000,423.000000
max,1459.000000,14.000000,4.000000,109.000000,1072.000000,1.000000,1.000000,3.000000,3.000000,1.000000,...,7.000000,2.000000,3.000000,3.000000,20.000000,11.000000,4.000000,8.000000,5.000000,662.000000

In [32]:
# 이제 싹 다 정수형으로 바뀜
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int16
 1   MSSubClass     1460 non-null   int8
 2   MSZoning       1460 non-null   int8
 3   LotFrontage    1460 non-null   int8
 4   LotArea        1460 non-null   int16
 5   Street         1460 non-null   int8
 6   Alley          1460 non-null   int8
 7   LotShape       1460 non-null   int8
 8   LandContour    1460 non-null   int8
 9   Utilities      1460 non-null   int8
 10  LotConfig      1460 non-null   int8
 11  LandSlope      1460 non-null   int8
 12  Neighborhood   1460 non-null   int8
 13  Condition1     1460 non-null   int8
 14  Condition2     1460 non-null   int8
 15  BldgType       1460 non-null   int8
 16  HouseStyle     1460 non-null   int8
 17  OverallQual    1460 non-null   int8
 18  OverallCond    1460 non-null   int8
 19  YearBuilt      1460 non-null   int8
 20  YearRemodAdd   1460 non-null   int8
 21  RoofStyle      1460 non-null   int8
 22  RoofMatl       1460 non-null   int8
 23  Exterior1st    1460 non-null   int8
 24  Exterior2nd    1460 non-null   int8
 25  MasVnrType     1460 non-null   int8
 26  MasVnrArea     1460 non-null   int16
 27  ExterQual      1460 non-null   int8
 28  ExterCond      1460 non-null   int8
 29  Foundation     1460 non-null   int8
 30  BsmtQual       1460 non-null   int8
 31  BsmtCond       1460 non-null   int8
 32  BsmtExposure   1460 non-null   int8
 33  BsmtFinType1   1460 non-null   int8
 34  BsmtFinSF1     1460 non-null   int16
 35  BsmtFinType2   1460 non-null   int8
 36  BsmtFinSF2     1460 non-null   int16
 37  BsmtUnfSF      1460 non-null   int16
 38  TotalBsmtSF    1460 non-null   int16
 39  Heating        1460 non-null   int8
 40  HeatingQC      1460 non-null   int8
 41  CentralAir     1460 non-null   int8
 42  Electrical     1460 non-null   int8
 43  1stFlrSF       1460 non-null   int16
 44  2ndFlrSF       1460 non-null   int16
 45  LowQualFinSF   1460 non-null   int8
 46  GrLivArea      1460 non-null   int16
 47  BsmtFullBath   1460 non-null   int8
 48  BsmtHalfBath   1460 non-null   int8
 49  FullBath       1460 non-null   int8
 50  HalfBath       1460 non-null   int8
 51  BedroomAbvGr   1460 non-null   int8
 52  KitchenAbvGr   1460 non-null   int8
 53  KitchenQual    1460 non-null   int8
 54  TotRmsAbvGrd   1460 non-null   int8
 55  Functional     1460 non-null   int8
 56  Fireplaces     1460 non-null   int8
 57  FireplaceQu    1460 non-null   int8
 58  GarageType     1460 non-null   int8
 59  GarageYrBlt    1460 non-null   int8
 60  GarageFinish   1460 non-null   int8
 61  GarageCars     1460 non-null   int8
 62  GarageArea     1460 non-null   int16
 63  GarageQual     1460 non-null   int8
 64  GarageCond     1460 non-null   int8
 65  PavedDrive     1460 non-null   int8
 66  WoodDeckSF     1460 non-null   int16
 67  OpenPorchSF    1460 non-null   int16
 68  EnclosedPorch  1460 non-null   int8
 69  3SsnPorch      1460 non-null   int8
 70  ScreenPorch    1460 non-null   int8
 71  PoolArea       1460 non-null   int8
 72  PoolQC         1460 non-null   int8
 73  Fence          1460 non-null   int8
 74  MiscFeature    1460 non-null   int8
 75  MiscVal        1460 non-null   int8
 76  MoSold         1460 non-null   int8
 77  YrSold         1460 non-null   int8
 78  SaleType       1460 non-null   int8
 79  SaleCondition  1460 non-null   int8
 80  SalePrice      1460 non-null   int16
dtypes: int16(14), int8(67)
memory usage: 135.6 KB

### Train Test Split

In [33]:
from sklearn.model_selection import train_test_split

X = train.drop(['SalePrice'], axis=1)
y = train['SalePrice']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=20)

### Decision Tree

In [74]:
from sklearn import tree

dectree = tree.DecisionTreeClassifier()

In [75]:
fittree = dectree.fit(X_train, y_train)

In [76]:
fittree.score(X_test, y_test)

0.0136986301369863

In [77]:
from sklearn.metrics import mean_squared_error

pred = fittree.predict(X_test)
RMSE = mean_squared_error(y_test, pred)**0.5

RMSE

63.615524296407784